spring.application.name=tpl-be-springboot
spring.datasource.url=jdbc:mysql://root:vvTtjnANxTOHpjQzOquFfIcFyxAfwHEH@interchange.proxy.rlwy.net:13019/railway
spring.datasource.username=root
spring.datasource.password=vvTtjnANxTOHpjQzOquFfIcFyxAfwHEH
spring.jpa.hibernate.ddl-auto=update
